version: '3'
services:
    flask:
        # you can base you .env file on exampleenv for deployment. Note that BASILICA_KEY should be replaced by a working API_KEY.
        env_file:
            - .env
        # This line tells docker-compose to build this container from the Dockerfile within ./flask
        build: ./flask
        container_name: flask
        restart: always
        # This project is not using ngnix, expose port :80 here to connect to the outside.
        ports:
            - 80:80
        # This defines the volumes the flask will use in case somehting needs to be saved or read.
        volumes:
            - web-data:/home/ubuntu/app/
        # Tells docker-compose that flask the flask container will call to the other containers.
        links:
            - postgres
        # Tells docker-compose this container needs postgres to be running.
        depends_on:
            - postgres
    postgres:
        # you can base you .env file on exampleenv for deployment. Important to note that whatever DB you hcnage you need to also change the URI of the DB.
        # Important to keep the information secret, please change in production.
        env_file:
            - .env
        restart: always
        image: postgres:latest
        container_name: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        # this was an older method of starting up the postgres container but decided to go with a .env for security
        # command: --name postgres-container -e POSTGRES_PASSWORD=password -it -p :5432 postgres

volumes:
    web-data:
    db-data:
